name: Trigger auto deployment for blognews-grupotrinta

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/blognews-grupotrinta-AutoDeployTrigger-5424129f-72fa-4c47-b172-484bf452c3d0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BLOGNEWSGRUPOTRINTA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrgrupotrinta.azurecr.io
          registryUsername: ${{ secrets.BLOGNEWSGRUPOTRINTA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BLOGNEWSGRUPOTRINTA_REGISTRY_PASSWORD }}
          containerAppName: blognews-grupotrinta
          resourceGroup: grupotrinta-fiap
          imageToBuild: acrgrupotrinta.azurecr.io/blognews:v1:${{ github.sha }}
          

     

